### ISSUE TITLE
Sohu extractor Does not work on 64bit Windows/python34

### ISSUE THREAD

**Issue by cowbert** [soimort/you-get#509]
I am trying to use this on windows 8.1 x86-64bit with Sohu videos.

With 64bit Python34 I get this error:
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

>c:\Python34\Scripts\you-get.exe "http://tv.sohu.com/20140116/n393624943.shtml" -y proxy.uku.im:8888
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\sohu.py", line 25, in sohu_download
    hqvid = data['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable

>c:\Python34\Scripts\you-get.exe "http://tv.sohu.com/20140116/n393624943.shtml" -x proxy.uku.im:8888 -y proxy.uku.im:8888
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\sohu.py", line 25, in sohu_download
    hqvid = data['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable
```
This should return a "you need to be in China mainland" error, but it doesn't, so it's not a proxy issue:
```
>c:\Python34\Scripts\you-get.exe "http://tv.sohu.com/20140116/n393624943.shtml"
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\sohu.py", line 25, in sohu_download
    hqvid = data['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable
```
I tried it with youtube and it works fine:
```
>c:\Python34\Scripts\you-get.exe "https://www.youtube.com/watch?v=i0o7lajjzBg"
site:                YouTube
title:               China's Elite Female Bodyguards
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          135.4 MiB (141968133 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading China's Elite Female Bodyguards.mp4 ...
  1.8% (  2.5/135.4MB) [=                                       ] 1/1
```

**Comment by jackyzy823** [comment]
Your piece of code is out of date. the bug is #353 and it's fixed in #489 . There're no release version after this fix. so you may clone you-get directly from github.

**Comment by cowbert** [comment]
I don't have git on this box, so I used the develop branch .zip file and it is giving me same error.
```
>c:\Python34\python.exe "c:\Users\cowbert\Downloads\you-get-develop\you-get" "http://tv.sohu.com/20140116/n393624943.shtml"
Traceback (most recent call last):
  File "c:\Users\cowbert\Downloads\you-get-develop\you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\__main__.py", line 91, in main
    main()
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\common.py", line 999, in main
    script_main('you-get', any_download, any_download_playlist)
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\common.py", line 785, in download_main
    download(url, **kwargs)
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\common.py", line 992, in any_download
    m.download(url, **kwargs)
  File "c:\Users\cowbert\Downloads\you-get-develop\src\you_get\extractors\sohu.py", line 27, in sohu_download
    hqvid = data['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by yan12125** [comment]
Seems you're outside Mainland China, so you need a proxy for correct downloading. For example:
```you-get -y "proxy.uku.im:8888" "http://tv.sohu.com/20140116/n393624943.shtml"```

**Comment by Hasset** [comment]
Still not work with the newest version on github (not release) @jackyzy823 
```bash
$ python3 ./you-get/you-get http://tv.sohu.com/20140318/n396785017.shtml
Video Site: Sohu.com
Title:      阿尔法屋第1季第5集
Type:       MPEG-4 video (video/mp4)
Size:       413.49 MiB (433580621 Bytes)

Downloading 阿尔法屋第1季第5集.mp4 ...
Traceback (most recent call last):
  File "./you-get/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/Volumes/RamDisk/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/Volumes/RamDisk/you-get/src/you_get/extractors/sohu.py", line 59, in sohu_download
    download_urls(urls, title, 'mp4', size, output_dir, refer = url, merge = merge)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 524, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 268, in url_save
    file_size = url_size(url, faker = faker)
  File "/Volumes/RamDisk/you-get/src/you_get/common.py", line 201, in url_size
    response = request.urlopen(url)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
